# Generated by Django 3.2.4 on 2021-08-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsiveApp', '0002_auto_20210807_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
    ]
