# Generated by Django 3.2.4 on 2021-08-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsiveApp', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-title',), 'verbose_name_plural': 'categories'},
        ),
    ]
